

POST https://6uwu2z82f1.execute-api.us-east-1.amazonaws.com/dev/customers

Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "emails": ["jane@example.com"],
  "privacySettings": {
    "marketingEmailsEnabled": true,
    "twoFactorEnabled": false
  }
}
