// App: Customer API
// path: test/http
// File: createCustomer.http
// Version: 0.1.0
// Author: ServerlessArchitectBot
// Date: 2025-06-18T00:22:49Z
// Description: Example HTTP request for creating a customer.

POST https://dd3j8swm80.execute-api.us-east-1.amazonaws.com/customers
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "firstName": "Jane",
  "lastName": "Doe",
  "emails": ["jane@example.com"],
  "privacySettings": {
    "marketingEmailsEnabled": true,
    "twoFactorEnabled": false
  }
}
