###
POST {{API_URL}}/customers
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "firstName": "John",
  "lastName": "Doe",
  "emails": ["john@example.com"],
  "privacySettings": {"marketingEmailsEnabled": true, "twoFactorEnabled": false}
}

> {%.status==202%}
