

POST https://hwwq3lpg0g.execute-api.us-east-1.amazonaws.com/dev/customers
Content-Type: application/json

{
  "id": "11111111-1111-1111-1111-111101111114",
  "firstName": "Bob",
  "middleName": "Q",
  "lastName": "Smith",
  "emails": ["alice@example.com"],
  "phoneNumbers": [{"type":"mobile","number":"+1234567890"}],
  "address": {
    "line1": "123 Main St",
    "city": "Metropolis",
    "state": "NY",
    "postalCode": "12345",
    "country": "US"
  },
  "privacySettings": {"marketingEmailsEnabled": true, "twoFactorEnabled": true}
}
