###
PUT {{API_URL}}/customers/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "firstName": "Jane",
  "lastName": "Doe",
  "emails": ["jane@example.com"],
  "privacySettings": {"marketingEmailsEnabled": true, "twoFactorEnabled": false}
}

> {%.status==202%}
