# App: Customer API
# path: .github/workflows
# File: ci.yml
# Version: 0.1.0
# Author: ServerlessArchitectBot
# Date: 2025-06-18T00:22:49Z
# Description: GitHub Actions workflow running lint, tests and Terraform
#              validation on each push.
#
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: terraform init -input=false
        working-directory: iac
      - run: terraform validate
        working-directory: iac
